:_mod-docs-content-type: PROCEDURE

[id="adding-gitlab-secrets_{context}"]
= Adding GitLab secrets

If you select GitLab as a CI provider and create an application. When you view the source code in GitLab you will see that the pipeline run has failed. The reason the pipeline run has failed is that it did not find GitLab and other secrets. Complete the following procedures to add the secrets.

.Prerequisites

* You have used the forked repository URL from link:https://github.com/redhat-appstudio/tssc-sample-templates[tssc-sample-templates] during the {ProductShortName} install process.

* You have already forked and cloned the link:https://github.com/redhat-appstudio/tssc-dev-multi-ci[tssc-dev-multi-ci] template.

* You must ensure your forked version is up to date and in sync with the upstream repository.

.Procedure

. Clone your forked `tssc-dev-multi-ci` repository, and then open it in your preferred text editor, such as Visual Studio Code.

. Create an `env_vars.sh` file that contains the following environment variables:

+
[source,bash]
----
# env_vars.sh

----

. Load the environment variables into your current shell session:

+
[source,bash]
----
source env_vars.sh
----

. Open terminal, and run the script that sets the variables in your GitLab repository

+
[source,bash]
----
chmod +x glab-set-vars
./glab-set-vars your_repository_name
----

. Run the script to verify the variables

+
[source,bash]
----
chmod +x glab-set-vars
./glab-get-vars your_repository_name
----
